### ISSUE TITLE
phase banner renders invalid html

### ISSUE THREAD

**Issue by jhackett1** [LBHackney-IT/lbh-frontend-react#720]
the phase banner component renders a block-level element (div) inside a paragraph tag. this isn't strictly allowed and triggers console errors in most browsers.

the [source component](https://lbh-frontend.herokuapp.com/components/lbh-phase-banner) doesn't show this problem:

```
<div class="govuk-phase-banner  lbh-phase-banner lbh-container">
  <p class="govuk-phase-banner__content">
    <strong class="govuk-tag govuk-phase-banner__content__tag  lbh-tag">
      Alpha
    </strong>
    <span class="govuk-phase-banner__text">
      This is a new website. Tell us what you think by leaving your feedback using the arrow at the bottom right of the screen.
    </span>
  </p>
</div>
```

**Comment by samtgarson** [comment]
To add some more detail to this issue for future: it's caused by the `div` tag in the `Paragraph` component, so a number of other components throw invalid HTML too: https://github.com/LBHackney-IT/lbh-frontend-react/blob/master/src/components/typography/Paragraph.tsx#L63)

It's unclear to me at this time what the underlying cause of this `div` element was for, potentially it could be replaced by a `span` to fix these.
